<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\SalesRecord;
use App\Models\SalesStatus;
use App\Models\SalesLeadSource;
use App\Models\SalesProduct;
use App\Models\SalesBusinessType;
use App\Models\State;
use App\Models\City;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class LeadGenApiController extends Controller
{
    /**
     * Get paginated leads generated by the current user.
     */
    public function getMyLeads(Request $request)
    {
        $user = $request->user();
        if (!$user) return response()->json(['message' => 'Unauthenticated'], 401);

        $perPage = $request->get('per_page', 10);

        $query = SalesRecord::with([
            'status',
            'prospectus',
            'city',
            'state',
            'businessType',
            'leadSource',
            'product',
            'latestRemark',
            'user'
        ])
        ->whereHas('assignmentLogs', function($aq) use ($user) {
            $aq->where('assigned_by', $user->id);
        });

        // Basic/Search query
        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function($q) use ($search) {
                $q->where('leads_name', 'like', "%{$search}%")
                  ->orWhere('contact_person', 'like', "%{$search}%")
                  ->orWhere('contact_number', 'like', "%{$search}%")
                  ->orWhere('email', 'like', "%{$search}%")
                  ->orWhere('address', 'like', "%{$search}%")
                  ->orWhereHas('prospectus', function($pq) use ($search) {
                      $pq->where('prospectus_name', 'like', "%{$search}%");
                  });
            });
        }

        // Filters
        if ($request->filled('status_id')) {
            $query->where('status_id', $request->status_id);
        }
        if ($request->filled('state_id')) {
            $query->where('state_id', $request->state_id);
        }
        if ($request->filled('city_id')) {
            $query->where('city_id', $request->city_id);
        }
        if ($request->filled('lead_source_id')) {
            $query->where('lead_source_id', $request->lead_source_id);
        }
        if ($request->filled('products_id')) {
            $query->where('products_id', $request->products_id);
        }
        if ($request->filled('business_type_id')) {
            $query->where('business_type_id', $request->business_type_id);
        }

        $records = $query->orderBy('createdat', 'desc')->paginate($perPage);

        return response()->json($records);
    }

    public function getFilterOptions(Request $request)
    {
        $statuses = []; 
        $states = []; 
        $businessTypes = []; 
        $leadSources = []; 
        $products = []; 
        $salesTeam = [];

        try { 
            $statuses = SalesStatus::orderBy('status_name')->get(['id', 'status_name']); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: statuses fetch failed: ' . $e->getMessage()); }

        try { 
            $states = State::orderBy('state_name')->get(['id', 'state_name']); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: states fetch failed: ' . $e->getMessage()); }

        try { 
            $businessTypes = SalesBusinessType::orderBy('business_name')->get(['id', 'business_name']); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: businessTypes fetch failed: ' . $e->getMessage()); }

        try { 
            $leadSources = SalesLeadSource::orderBy('source_name')->get(['id', 'source_name']); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: leadSources fetch failed: ' . $e->getMessage()); }

        try { 
            $products = SalesProduct::orderBy('product_name')->get(['id', 'product_name']); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: products fetch failed: ' . $e->getMessage()); }

        try { 
            $salesTeam = User::where('is_sales', 1)->select('id', 'name')->orderBy('name')->get(); 
        } catch (\Exception $e) { \Illuminate\Support\Facades\Log::warning('LeadGen API: salesTeam fetch failed: ' . $e->getMessage()); }

        return response()->json([
            'statuses' => $statuses,
            'states' => $states,
            'cities' => [],
            'business_types' => $businessTypes,
            'lead_sources' => $leadSources,
            'products' => $products,
            'sales_team' => $salesTeam
        ]);
    }

    /**
     * Get quick statistical counters for display cards.
     */
    public function getLeadGenStats(Request $request)
    {
        $user = $request->user();
        if (!$user) return response()->json(['message' => 'Unauthenticated'], 401);

        $baseQuery = SalesRecord::whereHas('assignmentLogs', function($aq) use ($user) {
            $aq->where('assigned_by', $user->id);
        });

        $todayFollowups = (clone $baseQuery)->whereDate('next_follow_up_date', Carbon::today())->count();
        $underProcess = (clone $baseQuery)->where('status_id', 2)->count();
        $completed = (clone $baseQuery)->where('status_id', 4)->count();
        $pending = (clone $baseQuery)->where('status_id', 5)->count();
        $todayNew = (clone $baseQuery)->where('status_id', 1)->count();

        // Fetch dynamic status group counts
        $statusCounts = SalesStatus::select('sales_statuses.id', 'sales_statuses.status_name')
            ->selectRaw('count(sales_records.id) as count')
            ->leftJoin('sales_records', function($join) use ($user) {
                $join->on('sales_statuses.id', '=', 'sales_records.status_id')
                     ->whereIn('sales_records.id', function($sub) use ($user) {
                          $sub->select('sales_record_id')
                              ->from('lead_assignment_logs')
                              ->where('assigned_by', $user->id);
                     });
            })
            ->groupBy('sales_statuses.id', 'sales_statuses.status_name')
            ->get();

        return response()->json([
            'summary' => [
                'today_followups' => $todayFollowups,
                'under_process' => $underProcess,
                'today_completed' => $completed,
                'today_pending' => $pending,
                'today_new' => $todayNew
            ],
            'status_counts' => $statusCounts
        ]);
    }

    /**
     * Reassign a generated lead to another executive.
     */
    public function reassignLeadGenLead(Request $request)
    {
        $user = $request->user();
        if (!$user) return response()->json(['message' => 'Unauthenticated'], 401);

        $leadId = $request->get('lead_id');
        $newUserId = $request->get('new_user_id');

        if (!$leadId || !$newUserId) {
            return response()->json(['success' => false, 'message' => 'Incomplete directive payload.'], 400);
        }

        // Find the lead generated by user
        $lead = SalesRecord::where('id', $leadId)
            ->whereHas('assignmentLogs', function($q) use ($user) {
                $q->where('assigned_by', $user->id);
            })
            ->first();

        if (!$lead) {
            return response()->json(['success' => false, 'message' => 'Target lead record not found within generated sets.'], 404);
        }

        $oldUserId = $lead->user_id;

        try {
            DB::transaction(function() use ($lead, $oldUserId, $newUserId, $user) {
                $lead->user_id = $newUserId;
                $lead->updatedat = now();
                $lead->save();

                \App\Models\LeadAssignmentLog::create([
                    'sales_record_id' => $lead->id,
                    'from_user_id' => $oldUserId,
                    'to_user_id' => $newUserId,
                    'assigned_by' => $user->id,
                    'remark' => 'Reallocated via Mobile Lead Gen module'
                ]);
            });

            $targetAgent = User::find($newUserId);

            return response()->json([
                'success' => true,
                'message' => 'Lead successfully reassigned to ' . ($targetAgent->name ?? 'New Executive')
            ]);

        } catch (\Exception $e) {
            return response()->json(['success' => false, 'message' => 'Operation rewrite failed: ' . $e->getMessage()], 500);
        }
    }

    /**
     * Save new generated lead record.
     */
    public function storeLeadGenLead(Request $request)
    {
        $user = $request->user();
        if (!$user) return response()->json(['message' => 'Unauthenticated'], 401);

        $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [
            'prospectus_id' => 'required|integer',
            'leads_name' => 'nullable|string',
            'contact_person' => 'nullable|string',
            'contact_number' => 'nullable|string',
            'status_id' => 'required|integer',
            'address' => 'nullable|string',
            'state_id' => 'nullable|integer',
            'city_id' => 'nullable|integer',
            'email' => 'nullable|email',
            'next_follow_up_date' => 'required|date',
            'business_type_id' => 'nullable|integer',
            'remark' => 'required|string',
            'website_link' => 'nullable|string',
            'lead_source_id' => 'nullable|integer',
            'products_id' => 'nullable|integer',
            'user_id' => 'required|integer'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Validation Failed',
                'errors' => $validator->errors()
            ], 422);
        }

        $validated = $validator->validated();

        $remarkText = $validated['remark'] ?? null;
        unset($validated['remark']);
        
        $validated['createdat'] = now();

        try {
            $salesRecord = DB::transaction(function() use ($validated, $remarkText, $user) {
                $record = SalesRecord::create($validated);

                \App\Models\LeadAssignmentLog::create([
                    'sales_record_id' => $record->id,
                    'from_user_id' => null,
                    'to_user_id' => $record->user_id,
                    'assigned_by' => $user->id,
                    'remark' => 'Allocated natively on Mobile creation'
                ]);

                if ($remarkText) {
                    \App\Models\Remark::create([
                        'remark_date' => now()->toDateString(),
                        'remark' => $remarkText,
                        'sales_remark_id' => $record->id
                    ]);
                }
                
                return $record;
            });

            return response()->json([
                'success' => true,
                'message' => 'Generated lead saved successfully!',
                'data' => $salesRecord
            ], 201);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Database storage failure: ' . $e->getMessage()
            ], 500);
        }
    }
}
